package pacman;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class PacmanJPanel extends javax.swing.JPanel {

    public Plansza plansza;
    public int menu=0;//id przycisków
    private Timer timer;
    private final int DELAY=150;
    public boolean gra=false;
    
    public PacmanJPanel() {
        initComponents();
        plansza=new Plansza();//tworzenie obiektu klasy Plansza
        addKeyListener(new Listener());//dodanie Listenera, aby "nasłuchiwał" klawiaturę
        timer=new Timer(DELAY,new Listener());
        timer.start();
    }
    
    private class Listener implements KeyListener,ActionListener{
        @Override
        public void keyTyped(KeyEvent ke) {
        }
        @Override
        public void keyPressed(KeyEvent ke){
            switch (ke.getKeyCode()){
                case KeyEvent.VK_UP://strzałka w górę
                    plansza.zmnienKierunekPacman(0);
                    break;
                case KeyEvent.VK_RIGHT://strzałaka w prawo
                    plansza.zmnienKierunekPacman(1);
                    break;
                case KeyEvent.VK_DOWN://strzałka w dół
                    plansza.zmnienKierunekPacman(2);
                    break;
                case KeyEvent.VK_LEFT://strzałka w lewo
                    plansza.zmnienKierunekPacman(3);
                    break;
                default:
                    return;
            }
            repaint();
        }
        @Override
        public void keyReleased(KeyEvent ke){
        }       

        @Override
        public void actionPerformed(ActionEvent ae){
            if(gra){
                plansza.update();
            }
            if(plansza.gra==2){//wygrana planszy
                plansza.gra=1;
                JOptionPane.showMessageDialog(PacmanJPanel.this, "Wygrałeś!");
                plansza.nastepnyPoziom();
            }else if(plansza.gra==0){//przegrana
                plansza.gra=1;
                JOptionPane.showMessageDialog(PacmanJPanel.this, "Przegrałeś!");
                menu=0;
                gra=false;
            }else if(plansza.gra==3){//wygrana gry
                plansza.gra=1;
                JOptionPane.showMessageDialog(PacmanJPanel.this, "Gratulacje! Wygrałeś wszystkie etapy!");
                menu=0;
            }
            repaint();
        }
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        switch (menu) {
            case 2://nowa gra
                plansza=new Plansza();
                menu=1;
            case 1://gramy dalej
                plansza.rysujPlansza(g2,this);      
                break;
            case 0://opis gry
                g2.drawString("Pacman (2 plansze)",50,50);
                g2.drawString("1.Zbierz wszystkie punkty",50,70);
                g2.drawString("2.Uciekaj przed duchami",50,90);
                g2.drawString("Powodzenia",50,110);
                g2.drawString("Mateusz Proskura IIST 4.5.2",50,130);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
